### ISSUE TITLE
sh:or can't be used in a property constraint.

### ISSUE THREAD

**Issue by him0** [labra/shaclex#11]
[SHACLE sh:or can be used in a property constraint](https://www.w3.org/TR/shacl/#OrConstraintComponent).

Following data can validate.
```
@prefix : <http://example.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .

:S a sh:Shape;
   sh:targetNode :x ;
   sh:or (
     [
         sh:property [
           sh:predicate :p ;
           sh:class :t1 ;
         ]
     ]
     [
         sh:property [
           sh:predicate :p ;
           sh:class :t2 ;
         ]
     ]
   ) .

:x :p [ a :t0 ] .
```

The same constraints definition following  can't validate.
```
@prefix : <http://example.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .

:S a sh:Shape;
   sh:targetNode :x ;
   sh:property [
      sh:predicate :p ;
      sh:or (
        [ sh:class :t0 ]
        [ sh:class :t1 ]
      ) ;
   ] .

:x :p [ a :t0 ] .
```

**Comment by labra** [comment]
You are right. It is a bug in SHACL processor. I am trying to see where is the problem.

**Comment by labra** [comment]
I have pushed a new version of the validator that solves the issue. 

The problem was in the [`component2Checker`](https://github.com/labra/shaclex/blob/master/modules/shacl/src/main/scala/es/weso/shacl/ValidatorCats.scala#L209) method which manually maps components from property constraints to node checkers. This method didn't have a mapping for `ClassComponent`. 

I have added other components, although in the future I would like to refactor that method to avoid the manual mappings.
