### ISSUE TITLE
shapeMap string argument to the Schema.validate method (SHACL validation)

### ISSUE THREAD

**Issue by berezovskyi** [labra/shaclex#99]
In the recent versions of shaclex, the Schema class no longer expects the ShapeMap object but instead a string. Before, we were passing ‘ShapeMap.parseShapeMap(OPTION_NONE)’ (OPTION_NONE is our Java constant for Option.apply(null) of type Option<String>). We tried passing an empty string or a compact Turtle serialisation of our Jena model, but it didn’t work (all of our cardinality tests fail).

When we further looked at how the ValidationTrigger.findTrigger works, it turned it deserialises the shapeMap string from a COMPACT representation, which does not seem to be a compact serialisation of Turtle. Another JSON option does not seem to be an option for JSON-LD. But then, this whole process only applies when the triggerName is SHAPEMAP, but by default it is TARGETDECLS (we pass ‘TargetDecls’ to the schema.validate() method).

Our case is that we have a Jena model with the SHACL shapes and we are ready to convert it to any RDF serialisation or use any SHACLEX factory to let it build some AST, but we are a bit lost here. Maybe we are doing things wrong before and your refactoring just brought attention to this.

cc @jadelkhoury @yashkhatri; ref: https://github.com/eclipse/lyo-validation/pull/14

**Comment by berezovskyi** [comment]
Maybe it helps to give some code.

This is how we invoked the validation method in 0.0.63:

```
        PrefixMap nodeMap = rdf.getPrefixMap();
        PrefixMap shapesMap = schema.pm();
        Map<String, scala.collection.immutable.List<String>> shapeMap = ShapeMap.parseShapeMap(
                OPTION_NONE);
        return schema.validate(rdf, TRIGGER_MODE, shapeMap, OPTION_NONE, OPTION_NONE, nodeMap,
                shapesMap);
```

This is how we tried to update it:

```
        PrefixMap nodeMap = rdf.getPrefixMap();
        PrefixMap shapesMap = schema.pm();
        final ShapeMap empty = ShapeMap.empty();
        final String shapeMap = empty.toString();
        return schema.validate(rdf, TRIGGER_MODE, shapeMap, OPTION_NONE, OPTION_NONE, nodeMap,
                               shapesMap);
```

The sample unit test assertion that fails as a result:

https://github.com/eclipse/lyo-validation/blob/6e30e67c0e7f1120f7b9d0ce5c5ceca8315cfe1e/src/test/java/org/eclipse/lyo/validation/ShaclInValidationTest.java#L69

**Comment by labra** [comment]
I am trying to figure out where is the change. I think you are talking about  `es.weso.shex.Schema` which is defined [here](https://github.com/labra/shaclex/blob/master/modules/schema/src/main/scala/es/weso/schema/Schema.scala), right?

**Comment by berezovskyi** [comment]
Yes, that's the right class. Also, `es.weso.schema.ShapeMap` seems to have moved to `es.weso.shapeMaps.ShapeMap`.

**Comment by labra** [comment]
I added a test case following your style of calling the library to the project [shexjava](https://github.com/labra/shexjava) that I created to show how to call the library from Java code [here](https://github.com/labra/shexjava/blob/master/src/test/java/es/weso/shexjava/ValidateTest.java) and it seems to work.

The parameter `shapeMap` is a String which represents the compact shape map. It is not currently used by the SHACL validator so you can just pass an empty string. You can see more information about shape maps [here](http://book.validatingrdf.com/bookHtml010.html#sec110). 

Although they are part of ShEx, they could be used also in SHACL in future versions, although they are ignored by now, so maybe the problem is different?

I did some changes to the way results are represented...is it possible that the problem is in the way you check the validation results?

**Comment by berezovskyi** [comment]
Thank you for clearing up the confusion regarding how we invoke shaclex validation methods! I filed another bug #100 about the actual validation report inconsistency.
